export declare const defaultOTBooks: {
    Genesis: number;
    Exodus: number;
    Leviticus: number;
    Numbers: number;
    Deuteronomy: number;
    Joshua: number;
    Judges: number;
    Ruth: number;
    "1 Samuel": number;
    "2 Samuel": number;
    "1 Kings": number;
    "2 Kings": number;
    "1 Chronicles": number;
    "2 Chronicles": number;
    Ezra: number;
    Nehemiah: number;
    Esther: number;
    Job: number;
    Psalms: number;
    Proverbs: number;
    Ecclesiastes: number;
    "Song of Solomon": number;
    Isaiah: number;
    Jeremiah: number;
    Lamentations: number;
    Ezekiel: number;
    Daniel: number;
    Hosea: number;
    Joel: number;
    Amos: number;
    Obadiah: number;
    Jonah: number;
    Micah: number;
    Nahum: number;
    Habakkuk: number;
    Zephaniah: number;
    Haggai: number;
    Zechariah: number;
    Malachi: number;
};
export declare const defaultNTBooks: {
    Matthew: number;
    Mark: number;
    Luke: number;
    John: number;
    Acts: number;
    Romans: number;
    "1 Corinthians": number;
    "2 Corinthians": number;
    Galatians: number;
    Ephesians: number;
    Philippians: number;
    Colossians: number;
    "1 Thessalonians": number;
    "2 Thessalonians": number;
    "1 Timothy": number;
    "2 Timothy": number;
    Titus: number;
    Philemon: number;
    Hebrews: number;
    James: number;
    "1 Peter": number;
    "2 Peter": number;
    "1 John": number;
    "2 John": number;
    "3 John": number;
    Jude: number;
    Revelation: number;
};
